name: 🚀 Deploy website on push

on:
  push:
    branches:
      - master
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: 🔨 Install dependencies and build project
        env:
          SMS_BASE_URL: ${{ secrets.SMS_BASE_URL }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
        run: |
          npm ci
          npm run build

          mkdir -p .next/standalone/.next
          cp -r .next/static .next/standalone/.next/static

          if [ -d "public" ]; then
              cp -r public .next/standalone/public
          fi

      - name: 📂 Sync standalone app
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./.next/standalone/
          server-dir: ./
          dangerous-clean-slate: true